### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mahxxd** [derNiklaas/node-mcc-api#2]
hey so i am making a mcc recreation and i have no idea how it works so if u can help me contact me on discord 
Matic Mahx#9461
plsss

**Comment by derNiklaas** [comment]
Hi there! I can help you with anything related to this project, but unfortunately I do not have time nor interest in recreating Noxcrew as they don't want public recreations and I respect their wish. 

Do you have any questions about this JavaScript/TypeScript wrapper for the MCC live API?
